name: Npm Update
on:
  schedule:
    - cron: 0 0 1 * *
    - cron: 0 0 28 * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Edit Version
        run: |
          id_run=$(echo ${{ github.run_id }} |cut -b 2-5)
          old="$(cat package.json |grep 'version'|head -1)"
          sed "s|$old|\"version\": \"23.$id_run.0beta\",|g" package.json > package2.json
          cat package2.json > package.json
          rm -rfv package2.json

      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Create Pull Request
        id: cpr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"